# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'   # e.g. v0.1.0

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ZIP
        run: |
          mkdir -p dist
          VERSION="${GITHUB_REF_NAME#v}"
          ZIP="dist/BlockRemover-${VERSION}.zip"
          zip -r "$ZIP" . -x '*.git*' -x '*node_modules*' -x 'dist/*' -x '.github/*'
          echo "ZIP=$ZIP" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: BlockRemover ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ZIP }}
          asset_name: ${{ env.ZIP }}
          asset_content_type: application/zip
